- hosts: terraform-ansible
  tasks:
  - name: criando o arquivo
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Meu primeiro projeto com terraform e ansible</h1>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"
    